export const elMenuTheme = {
  /* 
    '--el-menu-active-color': 'var(--el-color-primary)',
    '--el-menu-text-color': 'var(--el-text-color-primary)',
    '--el-menu-hover-text-color': 'var(--el-color-primary)',
    '--el-menu-bg-color': 'var(--el-fill-color-blank)',
    '--el-menu-hover-bg-color': 'var(--el-color-primary-light-9)',
    '--el-menu-item-height': '56px',
    '--el-menu-sub-item-height': 'calc(var(--el-menu-item-height) - 6px)',
    '--el-menu-horizontal-sub-item-height': '36px',
    '--el-menu-item-font-size': 'var(--el-font-size-base)',
    '--el-menu-item-hover-fill': 'var(--el-color-primary-light-9)',
    '--el-menu-border-color': 'var(--el-border-color)',
    '--el-menu-base-level-padding': '20px',
    '--el-menu-level-padding': '20px',
    '--el-menu-icon-width': '24px',
  */
  default: {
    'active-color': '#409EFF',
    'text-color': '#303133',
    'hover-text-color': '#409EFF',
    'bg-color': '#ffffff',
    'hover-bg-color': '#F5F7FA',
    'item-height': '56px',
    'sub-item-height': 'calc(var(--el-menu-item-height) - 6px)',
    'horizontal-sub-item-height': '36px',
    'item-font-size': '14px',
    'item-hover-fill': '#F5F7FA',
    'border-color': '#DCDFE6',
    'base-level-padding': '20px',
    'level-padding': '20px',
    'icon-width': '24px',
  },
  dark: {
    'active-color': '#409EFF',
    'text-color': '#E5EAF3',
    'hover-text-color': '#409EFF',
    'bg-color': '#141414',
    'hover-bg-color': '#1D1E1F',
    'item-height': '56px',
    'sub-item-height': 'calc(var(--el-menu-item-height) - 6px)',
    'horizontal-sub-item-height': '36px',
    'item-font-size': '14px',
    'item-hover-fill': '#1D1E1F',
    'border-color': '#303133',
    'base-level-padding': '20px',
    'level-padding': '20px',
    'icon-width': '24px',
  },
}
