import './common'
import './element-plus'
import './esri'
import '@vunk/core/index.css'
import '@vunk/form/index.css'
import './form'
import './layout/index.css'
import '@zzg6/flow/index.css'
import '@skzz/platform/index.css'

// for formaker
import 'mapbox-gl/dist/mapbox-gl.css'
import '@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw.css'
import '@vumap/core/index.css'
import '@vunk/formaker/index.css'
