/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IconExpand: typeof import('./src/components/icon-expand/index.vue')['default']
    IconFold: typeof import('./src/components/icon-fold/index.vue')['default']
    IconSearch: typeof import('./src/components/icon-search/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
